apiVersion: apps/v1
kind: Deployment
metadata:
  name: eip-sc-automation-frontend
  namespace: pptd-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eip-sc-automation-frontend
  template:
    metadata:
      labels:
        app: eip-sc-automation-frontend
    spec:
      containers:
        - name: eip-sc-automation-frontend-container
          image: amr-registry.caas.intel.com/pptd-prod/eip-sc-automation-frontend:v3.4
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "216Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
      imagePullSecrets:
        - name: regcred
